site_name: NC Technician Docs

markdown_extentsions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search
  - macros
  - roamlinks

theme:
  name: material